name: Deploy
on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment
        run: |
          npm install
          npm run deploy
        env:
          DO_API_KEY: ${{ secrets.DO_API_KEY }}
          DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
